### ISSUE TITLE
thx.Enums.string maximum call stack size exceeded

### ISSUE THREAD

**Issue by andypellucid** [fponticelli/thx.core#118]
```haxe
import thx.Enums;

enum MyEnum {
  Test(obj : { oldId: String, newId : String });
  None;
}

class Main {
  static function main() {
    trace(Enums.string(Test({ oldId: "1", newId: "2" })));
  }
}
```

Error appears to happen with enums that have parameters that are typed as plain objects.

**Comment by andypellucid** [comment]
```
/Users/awhite/temp/haxe-test/main.js:199
		for( var f in o ) {
		         ^

RangeError: Maximum call stack size exceeded
    at Function.Reflect.fields (/Users/awhite/temp/haxe-test/main.js:199:12)
    at Function.thx_Objects.string (/Users/awhite/temp/haxe-test/main.js:2621:23)
    at /Users/awhite/temp/haxe-test/main.js:2622:41
    at Array.map (native)
    at Function.thx_Objects.string (/Users/awhite/temp/haxe-test/main.js:2621:33)
    at /Users/awhite/temp/haxe-test/main.js:2622:41
    at Array.map (native)
    at Function.thx_Objects.string (/Users/awhite/temp/haxe-test/main.js:2621:33)
    at /Users/awhite/temp/haxe-test/main.js:2622:41
    at Array.map (native)
Error: Command failed with error 1
```
